name: Create Release

on:
  workflow_dispatch: {}

env:
  REGISTRY: ghcr.io

jobs:
  create-release:
    runs-on: ubuntu-latest
    steps:
      - name: "Checkout code"
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - uses: actions/setup-python@v4
        with:
          python-version: "3.12"

      - name: "Install requirements"
        run: pip install "bump-my-version==0.18.3" "generate-changelog==0.10.0"

      - name: "Setup git"
        run: git config --global user.email "you@example.com" && git config --global user.name "Your Name"

      - name: "Generate changelog"
        run: generate-changelog

      - name: "Bump version"
        run: bump-my-version bump minor

      - name: "Push it"
        run: git push --follow-tags

      - name: Log in to the Container registry
        uses: docker/login-action@65b78e6e13532edd9afa3aa52ac7964289d1a9c1
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}

      - name: "Build docker image"
        run: docker build . --platform linux/amd64 -t "ghcr.io/dmi-feo/test-releases:sometag"

      - name: "Push docker image"
        run: docker push "ghcr.io/dmi-feo/test-releases:sometag"
