name: Create Release

on:
  workflow_dispatch: {}

env:
  REGISTRY: ghcr.io

jobs:
  create-release:
    runs-on: ubuntu-latest
    steps:
      - name: "Checkout code"
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - uses: actions/setup-python@v4
        with:
          python-version: "3.12"

      - name: "Install requirements"
        run: pip install "bump-my-version==0.18.3" "generate-changelog==0.10.0"

      - name: "Setup git"
        run: git config --global user.email "you@example.com" && git config --global user.name "Your Name"

      - name: "Generate changelog"
        run: generate-changelog

      - name: "Bump version"
        run: bump-my-version bump minor

      - name: "Store version number"
        run: |
          echo "app_version=`git describe --tags --abbrev=0`" >> "$GITHUB_ENV"

      - name: Create Pull Request
        id: cpr
        uses: peter-evans/create-pull-request@v6
        with:
          title: "New version is coming: $app_version"
          branch: new-version-$app_version
# TAG AND VERSION
      - name: merge pr
        run: gh pr merge --squash --auto ${{ steps.cpr.outputs.pull-request-number }}
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Log in to the Container registry
        uses: docker/login-action@65b78e6e13532edd9afa3aa52ac7964289d1a9c1
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: "Build docker image"
        run: docker build . --platform linux/amd64 -t "ghcr.io/dmi-feo/test-releases:$app_version"

      - name: "Push docker image"
        run: docker push "ghcr.io/dmi-feo/test-releases:$app_version"
