name: Create Release

on:
  workflow_dispatch: {}

jobs:
  create-release:
    runs-on: ubuntu-latest
    steps:
      - name: "Checkout code"
        uses: actions/checkout@v4

      - name: "Bump version"
        run: make new-version-minor

      - name: "Create release"
        uses: actions/create-release@latest
